name: Setup MySQL

on:
  workflow_call:


jobs:
  create:
    name: Setup MySQL 8.0 LTS
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
        
      - name: Setup MySQL Client
        run: |
          sudo apt update
          sudo apt install mysql-client-core-8.0
      